### PR TITLE
Updates to compile successfully with fpc 3.2.0

### PR DESCRIPTION
**Pull request by sideshowbarker**
fpc 3.2.0 is apparently stricter about a few things, and our existing code has a couple of cases that cause fatal errors when compiling with fpc 3.2.0 — as well as a lot of cases that cause an informational message to get emitted that prevoius fpc versions did not emit for our code.

So in this PR branch, there are multiple commits:

1. A change that replaces the `Document.DocType` and `Document.DocumentElement` properties with `Document.GetDocType()` and `Document.GetDocumentElement()` methods in the `src/html/dom.pas` source, and updates the `src/wattsi.pas` application code to use the `Document.GetDocumentElement()` method. (The `Document.DocType` property was not actually used in the existing code.)

   Otherwise, without that change, fpc fails with these fatal errors:

   > dom.pas(120,55) Error: Record or object type expected
   > dom.pas(121,58) Error: Record or object type expected

   https://wiki.freepascal.org/User_Changes_Trunk#Property_field_access_lists_no_longer_allows_classes explains that the remedy for those errors is to do one of the following:

   * Switch the fields to records or objects
   * Use a method with inline modifier that will result in similar performance
   <br>
   So this change uses the second of those remedies.<br><br>

2. A change that marks the `Serialise()` function in `src/lib/ropes.pas` as an explicit (static) class function.

   Otherwise, without that change, fpc fails with these fatal errors:

   > ropes.pas(759,49) Error: Only class methods, class properties and class variables can be referred with class references
   > ropes.pas(770,49) Error: Only class methods, class properties and class variables can be referred with class references
   > ropes.pas(865,52) Error: Only class methods, class properties and class variables can be referred with class references

3. A change to causes fpc to suppress compiler messages of this form:

   > Note: Call to subroutine "arg1" marked as inline is not inlined

   Otherwise, without that change, fpc emits dozens of those messages.

### CODE REVIEW

**Comment by domenic** [comment]
Amazing stuff!

I wonder about fixing the warning messages, instead of suppressing them? Is it just a matter of removing a poorly-applied `inline` keyword, perhaps? http://free-pascal-general.1045716.n5.nabble.com/inlining-functions-depending-on-implementation-only-functions-td5732866.html seems to indicate that might be the best approach.

**Comment by sideshowbarker** [comment]
> I wonder about fixing the warning messages,

(Incidental aside: fpc doesn’t even classify these as warnings — and not even “Hints”, but instead just “Notes”. So I think in the fpc taxonomy, that “Note” designation essentially identifies them nothing-you-need-to-worry-about non-problems in practice.)

>  instead of suppressing them? Is it just a matter of removing a poorly-applied `inline` keyword, perhaps?

For the functions and procedures that are defined in our own code, yes, I guess the messages could be avoided by removing the `inline` keyword from the function/procedure definitions.

But as far as the `inline` keywords being poorly-applied: in spending some time looking at some of the cases, I can’t see any pattern or anything about them individually which makes it obvious that they couldn’t be inlined.

Of course the compiler is a lot smarter than me about figuring out something can’t be inlined. But it makes me wonder whether any other human being looking at the code — including somebody with a lot of Pascal experience — could identify which of those functions and procedures can’t be inlined, and why. It makes me curious to know what reproducible thought/analysis process a person could apply in order identify the cases that can’t be inlined. Or maybe I’m just missing something.

Anyway, there are quite a lot of them that we’d need to remove to avoid those messages. So it would be both a chore and also kind of an act of faith, unless we really understood clearly ourselves in each case why the particular function or procedure can’t be inlined.

But even if we were to remove all the cases from our own code, that wouldn’t get rid of all the messages — because there are actually cases where the compiler is reporting a function/procedure that’s defined in the Free Pascal standard runtime library; for example:

> fileutils.pas(63,4) Note: Call to subroutine "procedure Move(const source:<Formal type>;var dest:<Formal type>;count:Int64);" marked as inline is not inlined

As far as I understand, the `Move()` procedure that note is about is this:

https://www.freepascal.org/docs-html/rtl/system/move.html

So I guess the compiler is saying the source for that has the `inline` modifier. If so, it kind of surprises me the compiler hasn’t been made smart enough to recognize that as a procedure in the standard runtime library — and so something that it shouldn’t be emitting any messages about it. Because of course from our calling code we don’t have any way to anticipate that problem and to tell the compiler to not try to inline that.

**Comment by domenic** [comment]
I guess I'd still lean toward removing the inline annotations from our own code in general, as I don't trust humans to make inlining decisions. However, I don't have enough FreePascal experience to make that call definitively. And, the issue with the standard library means that it wouldn't even solve our problem, strangely enough. So OK, let's just merge this as-is :).

**Comment by domenic** [comment]
BTW, thanks very much for the nice separate commits each with detailed commit messages. Plus summarizing them in the PR description!

**Pull request merged**
