### PR TITLE
If errors were found, return exit status 1 on exit

### PR DESCRIPTION
**Pull request by sideshowbarker**

### CODE REVIEW

**Comment by domenic** [comment]
Will this break HTML CI builds, since HTML has lots of errors we haven't noticed? If so, we should probably fix HTML first...

**Comment by sideshowbarker** [comment]
Yeah it will break current builds due to those errors that have been getting suppressed. So yeah we should fix the errors in the HTML source first.

**Comment by domenic** [comment]
Should we fix html-build to output the wattsi output even with a zero exit code? It seems like wattsi might have interesting things to say that aren't errors...

**Comment by sideshowbarker** [comment]
> Should we fix html-build to output the wattsi output even with a zero exit code? It seems like wattsi might have interesting things to say that aren't errors...

We could but then we couldn't quiet it so that it’s silent of there are no errors. Which IMHO is not good.

So I think the real fix here is to also cause wattsi to always write errors to stderr instead of stdout. And the potentially-interesting stuff would just go to stdout. Which is still a little weird since it's not really output but there are other tools I can think of that do things that way.

Anyway, that way we could make it so that `html-build/build.sh` always by default passes on the stdout as well as the stderr—but then also have an option to ignore the wattsi stdout if you want to be completely silent in the no-errors-found case.

How does that sound?

**Comment by domenic** [comment]
I like that. It'll require a bit of build-server trickery to only deliver the desired output (we can't e.g. do a one file for stderr and one for stdout), but that's doable.

**Comment by zcorpan** [comment]
Wattsi currently errors if there's a bug in bugzilla with a URL that is doesn't have an id in `source`. We may want to change that so that someone can't break the build by filing a bug...

**Comment by sideshowbarker** [comment]
> Wattsi currently errors if there's a bug in bugzilla with a URL that is doesn't have an id in source. We may want to change that so that someone can't break the build by filing a bug...

Yeah, I think the logic in that wattsi source is such that we can distinguish among those errors clearly enough that a somebody-filed-a-new-bug case on its own would not result in a wattsi ending up reporting a non-zero exit status when he completed a spec build.

**Comment by sideshowbarker** [comment]
> Wattsi currently errors if there's a bug in bugzilla with a URL that is doesn't have an id in source. We may want to change that so that someone can't break the build by filing a bug...

PR #7 turns those cases into warnings that will not cause wattsi to end up exiting non-zero

**Comment by sideshowbarker** [comment]
Now that https://github.com/whatwg/html-build/pull/45 and #7 have landed, are we ready for this to be merged?

**Comment by domenic** [comment]
Let me send another PR to whatwg/html fixing the errors I introduced with the script layering stuff

**Comment by sideshowbarker** [comment]
> Let me send another PR to whatwg/html fixing the errors I introduced with the script layering stuff

ah yeah—ok, no rush

**Comment by sideshowbarker** [comment]
OK, with https://github.com/whatwg/html/pull/448 landed will merge this now

**Comment by sideshowbarker** [comment]
Merged in 4d114d994edd7710ae5b828fa801367a85b31175

**Pull request closed without merging**
