### PR TITLE
Update URL to fingerprint image

### PR DESCRIPTION
**Pull request by zcorpan**
See https://github.com/whatwg/whatwg.org/pull/64

### CODE REVIEW

**Comment by annevk** [comment]
So if we do this and not inline it, we should have maybe two resources on resources.whatwg.org. One for external usage and one for internal usage. WDYT?

**Comment by domenic** [comment]
Why would we need two?

**Comment by annevk** [comment]
@domenic as discussed in #whatwg, there's no need for ARIA and width/height information in the external variant as `` will take care of that.

**Comment by zcorpan** [comment]
But having those attribute there doesn't hurt either, it's just wasting a few bytes.

**Comment by domenic** [comment]
Hmm, I see. Why would we host an "internal variant" one then? Why not just use `` everywhere?

**Comment by zcorpan** [comment]
OK I've changed fingerprint.svg to omit the attributes.

**Comment by annevk** [comment]
Now that this is generalized to tracking vector changes to whatwg/html are needed too.

**Comment by annevk** [comment]
@sideshowbarker is this still okay? Need to make a few tweaks to the HTML PR but then this is ready to go.

**Pull request merged**
