### PR TITLE
Wrap heading section numbers in <span class=secno>

### PR DESCRIPTION
**Pull request by sideshowbarker**
Addresses #27.

### CODE REVIEW

**Comment by domenic** [comment]
Ah, sorry for not updating #27, but in https://github.com/whatwg/wattsi/pull/30#issuecomment-256282685 @annevk mentioned he'd prefer we only output this in the dev edition. I'm not sure that's a great idea personally---I can imagine our future selves getting very confused about the divergence in markup between the two while tweaking some stylesheets---but that's where we landed last time. @annevk, thoughts?

**Comment by annevk** [comment]
I'm somewhat indifferent at this point. My main quibble is that the generated HTML of Bikeshed is way out of proportion to what it could be I think so I'd rather not do anything just to match that, but if this help make progress just go ahead. It's a larger issue anyway.

**Comment by sideshowbarker** [comment]
> in #30 (comment) @annevk mentioned he'd prefer we only output this in the dev edition. I'm not sure that's a great idea personally---I can imagine our future selves getting very confused about the divergence in markup between the two while tweaking some stylesheets

If we do decide we only need it for the dev edition, I’m pretty sure it’s possible (maybe even easy) to make wattsi only do it for the dev edition

**Comment by domenic** [comment]
Let's merge this as-is then; although I understand @annevk's concerns in general, and applied them in #30 by removing my addition of Bikeshed's `heading` class, I feel more comfortable having the same markup structure between the two editions.

**Pull request merged**
