### PR TITLE
Align LICENSE with GitHub MIT template

### PR DESCRIPTION
**Pull request by annevk**

### CODE REVIEW

**Comment by annevk** [comment]
I think this should make GitHub recognize it as MIT, but I'm not a 100% sure.

**Review by foolip — APPROVED** [review]

**Comment by foolip** [comment]
@annevk seems like it didn't work, but maybe there's a caching layer here that we need to wait out?

I would guess that the leading "Parts" is the problem, and we could rewrite it to multiple copyright lines, one for each major contributor, and a final one that says "wattsi contributors" or something.

**Comment by annevk** [comment]
I'm personally okay with it now the non-copyright line part is aligned (and I verified it's MIT).

**Comment by foolip** [comment]
OK, let's leave it like this.

**Pull request merged**
