### PR TITLE
Remove <img src> rewriting and data-revision support

### PR DESCRIPTION
**Pull request by domenic**
Just removal; should be fine.

### CODE REVIEW

**Comment by domenic** [comment]
I think at this point we can let @sideshowbarker be a reviewer and not just Hixie, if he agrees.

**Comment by Hixie** [comment]
LGTM

**Comment by sideshowbarker** [comment]
> I think at this point we can let @sideshowbarker be a reviewer and not just Hixie, if he agrees.

Yeah, I would be happy to. I really like Wattsi both in terms of its features/behavior and also its code, so opportunities to help with it more would be kind of a labor of love.

**Comment by Hixie** [comment]
I...... can't tell if that's sarcasm... :-/

**Comment by sideshowbarker** [comment]
> I...... can't tell if that's sarcasm... :-/

hahah :-) Not sarcasm. More like .. pragmatism—in that, I think with regard to the various spec (pre)processors we’ve ever all used (or written) over the years, they all suck. So for the people working on any particular spec, I think it’s just a case of deciding on a “This one just sucks less” choice among them.

And I at least am pretty happy with the choice for HTML going forward to continue to be Wattsi (rather than, say, Bikeshed, which I think would otherwise be the objectively best choice for most any new spec that work starts up on).

So anyway I personally feel pretty good about having Wattsi and having it be the place where we make any needed enhancements when new requirements come along. It’s very fast in terms of its behavior—~8 seconds in my environment to do a complete regen of the spec (sans updates to the dependencies)—and it’s clear, understandable code (that compiles and builds easily and cleanly), etc.

**Comment by Hixie** [comment]
That's pretty much why I wrote it, yeah. I'm sad I couldn't get it even faster. :-(

**Pull request merged**
